import type { Metadata } from "next";
import { Geist, Geist_Mono, Lilita_One } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/Providers";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { NewSidebar } from "@/components/sidebar/newSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lilitaOne = Lilita_One({
  variable: "--font-lilita-one",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased ${lilitaOne.className}`}
      >
        <Providers>
          <NewSidebar />
          {/* <div className='absolute bottom-10 right-10 z-50'>
            <SidebarTrigger className='text-white border-2 border-white/20 h-10 w-10 rounded-2xl' />
          </div> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
